const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const ts = require('D:/DevEco Studio/tools/hvigor/hvigor/node_modules/typescript');
const source = fs.readFileSync('entry/src/main/ets/services/SpeechKitService.ets', 'utf8');
const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
let creates = 0, completeCreation;
const spoken = [], timers = new Map(); let timerId = 0;
const engine = { setListener(l) { this.listener = l; }, speak(text, params) { spoken.push({text, id: params.requestId}); }, stop() {}, shutdown() {} };
const api = { createEngine() { creates++; return new Promise(resolve => completeCreation = () => resolve(engine)); } };
const loaded = {};
vm.runInNewContext(js, { exports: loaded, require: () => ({textToSpeech: api}), setTimeout: (cb, ms) => { timers.set(++timerId, {cb,ms}); return timerId; }, clearTimeout: id => timers.delete(id), Date, Error });
const service = loaded.SpeechKitService;
const flush = async () => { for(let i=0;i<12;i++) await Promise.resolve(); };
(async () => {
  const prepare = service.prepare();
  const first = service.speakKey('一');
  const second = service.speakKey('二');
  assert.equal(creates, 1, 'initialization must be shared');
  completeCreation(); await prepare; await flush();
  assert.deepEqual(spoken.map(x=>x.text), ['一']);
  engine.listener.onComplete(spoken[0].id, {type:0}); await flush();
  assert.equal(spoken.length,1,'synthesis must not advance playback');
  assert.ok([...timers.values()][0].ms >=15000,'allow cold-start latency');
  engine.listener.onComplete(spoken[0].id,{type:1}); await first; await flush();
  assert.deepEqual(spoken.map(x=>x.text), ['一','二']);
  const cancelledSecond = second.catch(e=>e.message);
  const priority = service.speakPriority('全部清除'); await flush();
  assert.equal(await cancelledSecond,'播报已取消');
  assert.equal(spoken.at(-1).text,'全部清除','missing stop callback must not block priority');
  engine.listener.onError(spoken[1].id,1,'late error');
  engine.listener.onStop(spoken[1].id);
  engine.listener.onComplete(spoken.at(-1).id,{type:1}); await priority;
  await service.release();
  const cancelled = service.speakKey('三').catch(e=>e.message);
  service.stopSpeaking();
  const replacement = service.speakKey('四');
  completeCreation(); await flush();
  assert.equal(await cancelled,'播报已取消');
  assert.equal(spoken.at(-1).text,'四');
  assert.ok(!spoken.some(x=>x.text==='三'),'cancelled initialization task must not speak');
  const timedOut = replacement.catch(e=>e.message);
  [...timers.values()][0].cb();
  assert.equal(await timedOut,'语音播报超时，请重试');
  await service.release();
  const pending = service.speakKey('五').catch(e=>e.message);
  await service.release(); completeCreation(); await flush();
  assert.equal(await pending,'播报已取消');
  assert.ok(!spoken.some(x=>x.text==='五'),'released task must not resume');
  console.log('PASS: shared initialization, ordered full playback, cancellation, stale callbacks, timeout failure, release during initialization');
})().catch(e=>{console.error(e);process.exitCode=1;});

